# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Moving Minimum (Erosion) in C++
#'
#' Same result as `erode()`, computed with a monotone queue so the work
#' does not grow with the window size. The queue holds positions whose
#' values increase from front to back. A new value removes every larger
#' value from the back, positions that have left the window are removed
#' from the front, and the front is the minimum of the current window.
#'
#' @param g Numeric vector.
#' @param m Window half width, in number of points.
#'
#' @return A numeric vector the same length as `g`.
#'
#' @references
#' Lemire, D. (2006). Streaming maximum-minimum filter using no more than
#' three comparisons per element. Nordic Journal of Computing, 13(4),
#' 328 to 339.
#'
#' @keywords internal
erode_cpp <- function(g, m) {
    .Call(`_hullBase_erode_cpp`, g, m)
}

#' Lower Hull Vertices in C++
#'
#' Andrew's monotone chain for the lower convex hull. For three points O,
#' A and B, A is removed while the cross product
#' `(xA - xO) * (yB - yO) - (yA - yO) * (xB - xO)` is zero or less.
#'
#' @param x Numeric vector of wavenumbers, sorted increasing.
#' @param y Numeric vector of values in the same order.
#'
#' @return Integer vector of the positions (starting at 1) of the hull
#'   vertices, from left to right.
#'
#' @keywords internal
lower_hull_cpp <- function(x, y) {
    .Call(`_hullBase_lower_hull_cpp`, x, y)
}

